version: "3.6"
services:
  # Wordpress auto configuration
  # depends on wp-cli build
  wp-auto-config:
    image: wpcli
    build: ./wpcli/
    container_name: ${COMPOSE_PROJECT_NAME}_wp_autoconfig
    entrypoint: sh -c "/wait && make -f /scripts/Makefile"
    volumes:
      - ${WORDPRESS_DATA_DIR}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - database
    environment:
      # Waiting for MySQL and wordpress -------------------
      - WAIT_HOSTS=database:3306,wordpress:80
      - WAIT_BEFORE=${WAIT_BEFORE:-30}
      - WAIT_AFTER=${WAIT_AFTER:-15}
      - WAIT_TIMEOUT=${WAIT_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
      # Wordpress configuration -----------------------------
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE}
      - WORDPRESS_THEME=${WORDPRESS_THEME}
      - WORDPRESS_CHILD_THEME=${WORDPRESS_CHILD_THEME}
      - WORDPRESS_PLUGINS=${WORDPRESS_PLUGINS}
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
      - WORDPRESS_DB_HOST=${DATABASE_HOST}
      - WORDPRESS_DB_USER=${DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_WEBSITE_TITLE=${WORDPRESS_WEBSITE_TITLE}
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL}
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=${WORDPRESS_WEBSITE_URL_WITHOUT_HTTP}
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE=${WORDPRESS_WEBSITE_POST_URL_STRUCTURE:-"/blog/%postname%/"}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
